const fs = require('fs');
const os = require('os');
const path = require('path');

const ENV_PATH = path.join(__dirname, '..', '.env.local');
const DEFAULT_EXPO_PORT = '8081';

const ADAPTER_PREFERENCE_PATTERNS = [
  { pattern: /(wi[-\s]?fi|wireless|wlan)/i, score: 120 },
  { pattern: /(ethernet|eth)/i, score: 80 },
  { pattern: /(local area connection)/i, score: 50 }
];

const ADAPTER_BLOCK_PATTERNS = [
  /loopback/i,
  /docker/i,
  /wsl/i,
  /hyper-v/i,
  /virtual/i,
  /vmware/i,
  /vbox/i,
  /vpn/i,
  /tunnel/i,
  /tap/i,
  /tailscale/i,
  /zerotier/i
];

function isPrivateLanIp(ip) {
  return (
    ip.startsWith('10.') ||
    ip.startsWith('192.168.') ||
    /^172\.(1[6-9]|2\d|3[0-1])\./.test(ip)
  );
}

function scoreInterface(interfaceName, addressInfo) {
  let score = 0;

  if (isPrivateLanIp(addressInfo.address)) {
    score += 100;
  }

  for (const { pattern, score: weight } of ADAPTER_PREFERENCE_PATTERNS) {
    if (pattern.test(interfaceName)) {
      score += weight;
    }
  }

  if (/^192\.168\./.test(addressInfo.address)) {
    score += 25;
  }

  return score;
}

function isBlockedInterface(interfaceName) {
  return ADAPTER_BLOCK_PATTERNS.some((pattern) => pattern.test(interfaceName));
}

function collectCandidates() {
  const interfaces = os.networkInterfaces();
  const candidates = [];

  for (const [interfaceName, addresses] of Object.entries(interfaces)) {
    if (!Array.isArray(addresses) || isBlockedInterface(interfaceName)) {
      continue;
    }

    for (const info of addresses) {
      const family = typeof info.family === 'string' ? info.family : String(info.family);
      if (
        family !== 'IPv4' ||
        info.internal ||
        info.address === '127.0.0.1' ||
        info.address.startsWith('169.254.')
      ) {
        continue;
      }

      candidates.push({
        interfaceName,
        address: info.address,
        score: scoreInterface(interfaceName, info)
      });
    }
  }

  return candidates.sort((a, b) => b.score - a.score);
}

function chooseBestLanIp() {
  const candidates = collectCandidates();
  if (candidates.length === 0) {
    return null;
  }

  return candidates[0];
}

function writeEnvFile(ip) {
  const envContent = [
    '# Auto-generated by scripts/setupExpoLan.js',
    `REACT_NATIVE_PACKAGER_HOSTNAME=${ip}`,
    `EXPO_PUBLIC_DEV_LAN_IP=${ip}`,
    ''
  ].join('\n');

  fs.writeFileSync(ENV_PATH, envContent, 'utf8');
}

function setupExpoLan() {
  const selected = chooseBestLanIp();

  if (!selected) {
    console.warn('[expo-lan] No suitable LAN IPv4 detected. Falling back to localhost.');
    return {
      ip: '127.0.0.1',
      expoUrl: `exp://127.0.0.1:${DEFAULT_EXPO_PORT}`,
      wroteEnv: false
    };
  }

  writeEnvFile(selected.address);

  const expoUrl = `exp://${selected.address}:${DEFAULT_EXPO_PORT}`;
  console.log(`[expo-lan] Selected LAN IP: ${selected.address} (${selected.interfaceName})`);
  console.log(`[expo-lan] Expected Expo URL: ${expoUrl}`);
  console.log(`[expo-lan] Backend API base target: http://${selected.address}:8080`);
  console.log(`[expo-lan] Wrote ${path.relative(path.join(__dirname, '..'), ENV_PATH)}.`);

  return {
    ip: selected.address,
    expoUrl,
    wroteEnv: true,
    interfaceName: selected.interfaceName
  };
}

if (require.main === module) {
  setupExpoLan();
}

module.exports = {
  setupExpoLan,
  chooseBestLanIp
};
